GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/11

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "Jonas Willaim",
  "subscribedToChannel": "GAMEPAUSE"
}

